export const KEY_DATA = [
  { value: '`', code: 'Backquote' },
  { value: '1', code: 'Digit1' },
  { value: '2', code: 'Digit2' },
  { value: '3', code: 'Digit3' },
  { value: '4', code: 'Digit4' },
  { value: '5', code: 'Digit5' },
  { value: '6', code: 'Digit6' },
  { value: '7', code: 'Digit7' },
  { value: '8', code: 'Digit8' },
  { value: '9', code: 'Digit9' },
  { value: '0', code: 'Digit0' },
  { value: '-_', code: 'Minus' },
  { value: '=+', code: 'Equal' },
  { value: 'Backspace', code: 'Backspace' },
  { value: 'Tab', code: 'Tab' },
  { value: 'Q', code: 'KeyQ' },
  { value: 'W', code: 'KeyW' },
  { value: 'E', code: 'KeyE' },
  { value: 'R', code: 'KeyR' },
  { value: 'T', code: 'KeyT' },
  { value: 'Y', code: 'KeyY' },
  { value: 'U', code: 'KeyU' },
  { value: 'I', code: 'KeyI' },
  { value: 'O', code: 'KeyO' },
  { value: 'P', code: 'KeyP' },
  { value: '[{', code: 'BracketLeft' },
  { value: ']}', code: 'BracketRight' },
  { value: '\\|', code: 'Backslash' },
  { value: 'CapsLock', code: 'CapsLock' },
  { value: 'A', code: 'KeyA' },
  { value: 'S', code: 'KeyS' },
  { value: 'D', code: 'KeyD' },
  { value: 'F', code: 'KeyF' },
  { value: 'G', code: 'KeyG' },
  { value: 'H', code: 'KeyH' },
  { value: 'J', code: 'KeyJ' },
  { value: 'K', code: 'KeyK' },
  { value: 'L', code: 'KeyL' },
  { value: ';:', code: 'Semicolon' },
  { value: `'"`, code: 'Quote' },
  { value: 'Enter', code: 'Enter' },
  { value: 'Shift', code: 'ShiftLeft' },
  { value: 'Z', code: 'KeyZ' },
  { value: 'X', code: 'KeyX' },
  { value: 'C', code: 'KeyC' },
  { value: 'V', code: 'KeyV' },
  { value: 'B', code: 'KeyB' },
  { value: 'N', code: 'KeyN' },
  { value: 'M', code: 'KeyM' },
  { value: ',<', code: 'Comma' },
  { value: '.>', code: 'Period' },
  { value: '/?', code: 'Slash' },
  { value: 'Shift', code: 'ShiftRight' },
  { value: 'Control', code: 'ControlLeft' },
  { value: 'Alt', code: 'AltLeft' },
  { value: 'Space', code: 'Space' },
  { value: 'Alt', code: 'AltRight' },
  { value: 'Control', code: 'ControlRight' },
];

/*
export const KEY_DATA = [
  { id: '`', value: '`', code: 'Backquote' },
  { id: '1', value: '1', code: 'Digit1' },
  { id: '2', value: '2', code: 'Digit2' },
  { id: '3', value: '3', code: 'Digit3' },
  { id: '4', value: '4', code: 'Digit4' },
  { id: '5', value: '5', code: 'Digit5' },
  { id: '6', value: '6', code: 'Digit6' },
  { id: '7', value: '7', code: 'Digit7' },
  { id: '8', value: '8', code: 'Digit8' },
  { id: '9', value: '9', code: 'Digit9' },
  { id: '0', value: '0', code: 'Digit0' },
  { id: '-`', value: '-_', code: 'Minus' },
  { id: '=', value: '=+', code: 'Equal' },
  { id: 'backspace', value: 'Backspace', code: 'Backspace' },
  { id: 'tab', value: 'Tab', code: 'Tab' },
  { id: 'q', value: 'Q', code: 'KeyQ' },
  { id: 'w', value: 'W', code: 'KeyW' },
  { id: 'e', value: 'E', code: 'KeyE' },
  { id: 'r', value: 'R', code: 'KeyR' },
  { id: 't', value: 'T', code: 'KeyT' },
  { id: 'y', value: 'Y', code: 'KeyY' },
  { id: 'u', value: 'U', code: 'KeyU' },
  { id: 'i', value: 'I', code: 'KeyI' },
  { id: 'o', value: 'O', code: 'KeyO' },
  { id: 'p', value: 'P', code: 'KeyP' },
  { id: '[{', value: '[{', code: 'BracketLeft' },
  { id: ']}', value: ']}', code: 'BracketRight' },
  { id: 'backslash', value: '\\|', code: 'Backslash' },
  { id: 'capslock', value: 'CapsLock', code: 'CapsLock' },
  { id: 'a', value: 'A', code: 'KeyA' },
  { id: 's', value: 'S', code: 'KeyS' },
  { id: 'd', value: 'D', code: 'KeyD' },
  { id: 'f', value: 'F', code: 'KeyF' },
  { id: 'g', value: 'G', code: 'KeyG' },
  { id: 'h', value: 'H', code: 'KeyH' },
  { id: 'j', value: 'J', code: 'KeyJ' },
  { id: 'k', value: 'K', code: 'KeyK' },
  { id: 'l', value: 'L', code: 'KeyL' },
  { id: ';:', value: ';:', code: 'Semicolon' },
  { id: "''", value: `'"`, code: 'Quote' },
  { id: 'enter', value: 'Enter', code: 'Enter' },
  { id: 'lshift', value: 'Shift', code: 'ShiftLeft' },
  { id: 'z', value: 'Z', code: 'KeyZ' },
  { id: 'x', value: 'X', code: 'KeyX' },
  { id: 'c', value: 'C', code: 'KeyC' },
  { id: 'v', value: 'V', code: 'KeyV' },
  { id: 'b', value: 'B', code: 'KeyB' },
  { id: 'n', value: 'N', code: 'KeyN' },
  { id: 'm', value: 'M', code: 'KeyM' },
  { id: ',<', value: ',<', code: 'Comma' },
  { id: '.>', value: '.>', code: 'Period' },
  { id: '/?', value: '/?', code: 'Slash' },
  { id: 'rshift', value: 'Shift', code: 'ShiftRight' },
  { id: 'lcontrol', value: 'Control', code: 'ControlLeft' },
  { id: 'lalt', value: 'Alt', code: 'AltLeft' },
  { id: 'spacebar', value: 'Space', code: 'Space' },
  { id: 'ralt', value: 'Alt', code: 'AltRight' },
  { id: 'rcontrol', value: 'Control', code: 'ControlRight' },
];

*/
