export const KEY_DATA = [
  { value: '`', code: 'Backquote' },
  { value: '1', code: 'Digit1' },
  { value: '2', code: 'Digit2' },
  { value: '3', code: 'Digit3' },
  { value: '4', code: 'Digit4' },
  { value: '5', code: 'Digit5' },
  { value: '6', code: 'Digit6' },
  { value: '7', code: 'Digit7' },
  { value: '8', code: 'Digit8' },
  { value: '9', code: 'Digit9' },
  { value: '0', code: 'Digit0' },
  { value: '-_', code: 'Minus' },
  { value: '=+', code: 'Equal' },
  { value: 'Backspace', code: 'Backspace' },
  { value: 'Tab', code: 'Tab' },
  { value: 'Q', code: 'KeyQ' },
  { value: 'W', code: 'KeyW' },
  { value: 'E', code: 'KeyE' },
  { value: 'R', code: 'KeyR' },
  { value: 'T', code: 'KeyT' },
  { value: 'Y', code: 'KeyY' },
  { value: 'U', code: 'KeyU' },
  { value: 'I', code: 'KeyI' },
  { value: 'O', code: 'KeyO' },
  { value: 'P', code: 'KeyP' },
  { value: '[{', code: 'BracketLeft' },
  { value: ']}', code: 'BracketRight' },
  { value: '\\|', code: 'Backslash' },
  { value: 'CapsLock', code: 'CapsLock' },
  { value: 'A', code: 'KeyA' },
  { value: 'S', code: 'KeyS' },
  { value: 'D', code: 'KeyD' },
  { value: 'F', code: 'KeyF' },
  { value: 'G', code: 'KeyG' },
  { value: 'H', code: 'KeyH' },
  { value: 'J', code: 'KeyJ' },
  { value: 'K', code: 'KeyK' },
  { value: 'L', code: 'KeyL' },
  { value: ';:', code: 'Semicolon' },
  { value: `'"`, code: 'Quote' },
  { value: 'Enter', code: 'Enter' },
  { value: 'Shift', code: 'ShiftLeft' },
  { value: 'Z', code: 'KeyZ' },
  { value: 'X', code: 'KeyX' },
  { value: 'C', code: 'KeyC' },
  { value: 'V', code: 'KeyV' },
  { value: 'B', code: 'KeyB' },
  { value: 'N', code: 'KeyN' },
  { value: 'M', code: 'KeyM' },
  { value: ',<', code: 'Comma' },
  { value: '.>', code: 'Period' },
  { value: '/?', code: 'Slash' },
  { value: 'Shift', code: 'ShiftRight' },
  { value: 'Control', code: 'ControlLeft' },
  { value: 'Alt', code: 'AltLeft' },
  { value: 'Space', code: 'Space' },
  { value: 'Alt', code: 'AltRight' },
  { value: 'Control', code: 'ControlRight' },
];

export const FORBIDDEN_KEY_DATA_LIST = [
  { value: 'Tab', code: 'Tab' },
  { value: 'Clear', code: 'Clear' },
  { value: 'Control', code: 'ControlLeft' },
  { value: 'Alt', code: 'AltLeft' },
  { value: 'Pause', code: 'Pause' },
  { value: 'Lang2', code: 'Lang2' },
  { value: 'PageUp', code: 'PageUp' },
  { value: 'PageDown', code: 'PageDown' },
  { value: 'End', code: 'End' },
  { value: 'Home', code: 'Home' },
  { value: 'ArrowLeft', code: 'ArrowLeft' },
  { value: 'ArrowUp', code: 'ArrowUp' },
  { value: 'ArrowRight', code: 'ArrowRight' },
  { value: 'ArrowDown', code: 'ArrowDown' },
  { value: 'Insert', code: 'Insert' },
  { value: 'Delete', code: 'Delete' },
  { value: 'MetaLeft', code: 'MetaLeft' },
  { value: 'F1', code: 'F1' },
  { value: 'F2', code: 'F2' },
  { value: 'F3', code: 'F3' },
  { value: 'F4', code: 'F4' },
  { value: 'F5', code: 'F5' },
  { value: 'F6', code: 'F6' },
  { value: 'F7', code: 'F7' },
  { value: 'F8', code: 'F8' },
  { value: 'F9', code: 'F9' },
  { value: 'F10', code: 'F10' },
  { value: 'F11', code: 'F11' },
  { value: 'F12', code: 'F12' },
  { value: 'NumLock', code: 'NumLock' },
  { value: 'ScrollLock', code: 'ScrollLock' },
];

export const FORBIDDEN_KEY_DATA = {
  Tab: true,
  Clear: true,
  ControlLeft: true,
  AltLeft: true,
  Pause: true,
  Lang2: true,
  PageUp: true,
  PageDown: true,
  End: true,
  Home: true,
  ArrowLeft: true,
  ArrowUp: true,
  ArrowRight: true,
  ArrowDown: true,
  Insert: true,
  Delete: true,
  MetaLeft: true,
  F1: true,
  F2: true,
  F3: true,
  F4: true,
  F5: true,
  F6: true,
  F7: true,
  F8: true,
  F9: true,
  F10: true,
  F11: true,
  F12: true,
  NumLock: true,
  ScrollLock: true,
};
